name: akave

services:
  akave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: akave
    ports:
      - "8000:3000"
    env_file:
      - .env
    environment:
      - NODE_ADDRESS=connect.akave.ai:5500
    restart: unless-stopped
    network_mode: "host"
