name: mcp-server

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "3001:3001"
    volumes:
      - ./scripts:/app/scripts
      - ./.env:/app/.env
      - mcp_server_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    network_mode: "host"

volumes:
  mcp_server_node_modules:
